export { Vector3, AxisRecordDefinition, V } from './Vector3.js'
export type { Vec3 } from './Vector3.js'
export { parseAst } from './render.js'
export { compile } from './compile/compile.js'
export { serializeToJson } from './compile/serialize-json.js'
export type { JsonScene, JsonMesh, JsonTriangle, JsonVertex } from './compile/serialize-json.js'
export { Shape, ShapeType } from './shapes/index.js'
export { RenderOptions } from './compile/types.js'
export { Colors } from './Colors.js'
export type { TProps } from './shapes/index.js'
export { validateShapes, createValidator } from './compile/validate-shapes.js'
